# List of actor definitions
actors:
  - name: Horn
    type: HORN
    uid:
    output:
  - name: Light
    type: LIGHT
    uid:
    output:
  - name: Igniter
    type: TRIGGER
    uid:
    output:
  - name: NitrousMain
    type: SERVO
    uid:
    output:
  - name: NitrousVent
    type: SERVO
    uid:
    output:
  - name: NitrousFill
    type: SERVO
    uid:
    output:
  - name: N2Pressure
    type: SERVO
    uid:
    output:
  - name: N2Purge
    type: SOLENOID
    uid:
    output:

# List of sensor definitions
sensors:
  - name:
    type:
    uid:
    input: