# List of actor definitions
actors:
  - name: Horn
    type: 2f6L
    uid: UbQ
    output: 2
  - name: Light
    type: LIGHT
    uid: UbQ
    output: 0
  - name: Igniter
    type: TRIGGER
    uid: 2f6L
    output: 0
  - name: NitrousMain
    type: SERVO
    uid: 2cPc
    output: 0
  - name: NitrousVent
    type: SERVO
    uid: 2cPc
    output: 1
  - name: NitrousFill
    type: SERVO
    uid: 2cPc
    output: 2
  - name: N2Pressure
    type: SERVO
    uid: 2cPc
    output: 3
  - name: N2Purge
    type: SOLENOID
    uid: 2f6L
    output: 1
  - name: SegmentDisplay
    type:
    uid:
    output:

# List of sensor definitions
sensors:
  - name: Pressure 1
    type: PRESSURE
    uid: TODO
    port: -1
    pin: -1
  - name: Pressure 2
    type: PRESSURE
    uid: TODO
    port: -1
    pin: -1
  - name: Pressure 3
    type: PRESSURE
    uid: TODO
    port: -1
    pin: -1
  - name: Pressure 4
    type: PRESSURE
    uid: TODO
    port: -1
    pin: -1
  - name: Temperatur 1
    type: TEMPERATURE
    uid: TODO
    port: -1
    pin: -1
  - name: Temperatur 2
    type: TEMPERATURE
    uid: TODO
    port: -1
    pin: -1
  - name: Load cell 1
    type: LOAD
    uid: TODO
    port: -1
    pin: -1
  - name: Load cell 2
    type: LOAD
    uid: TODO
    port: -1
    pin: -1
  - name: Differential pressure
    type: DIFFERENTIAL_PRESSURE
    uid: TODO
    port: -1
    pin: -1