# List of actor definitions
actors:
  - name: Horn
    type: HORN
    uid: 2f6L
    output: 0
  - name: Light
    type: LIGHT
    uid: 2f6L
    output: 1
  - name: Igniter
    type: TRIGGER
    uid: 2f6L
    output: 0
  - name: N20MainValve #renmaed from NitrousMain
    type: SERVO
    uid: 2cPc
    output: 2
    min_position: 0
    max_position: -8772
  - name: N20VentValve # rename from  NitrousVent
    type: SERVO
    uid: 2cPc
    output: 1
    min_position: 0
    max_position: 6050 #max position do not change
  - name: N20FillValve #renamed from NitrousFill
    type: SERVO
    uid: 2cPc
    output: 0
    min_position: 0
    max_position: 6050
  - name: N2PressureValve #renamed from N2Pressure
    type: SERVO
    uid: 2cPc
    output: 3
    min_position: 0
    max_position: 5150
  - name: N2PurgeValve #renmaned from N2Purge
    type: SERVO
    uid: 2cPc
    output: 4
    min_position: 0
    max_position: 5070
  - name: QuickDisconnect
    type: SOLENOID
    uid: 2f6L
    output: 4
    min_position: 0
    max_position: 6000
  - name: SegmentDisplay
    type: COUNTER
    uid: 256T
    output: -1

# List of sensor definitions
sensors:
  - name: Pressure 0
    type: PRESSURE
    uid: 27AM
    channel: 0
    period: 5
  - name: Pressure 1
    type: PRESSURE
    uid: 27AM
    channel: 1
    period: 5
  - name: Pressure 2
    type: PRESSURE
    uid: 27AQ
    channel: 1
    period: 5
  - name: Differential Nitrous pressure
    type: PRESSURE
    uid: 27AQ
    channel: 0
    period: 5
  - name: Temperatur Nitrous
    type: TEMPERATURE
    uid: 2f1R
    channel: -1 # not used
    period: 5
  - name: Temperatur Engine
    type: TEMPERATURE
    uid: 2eZV
    channel: -1 # not used
    period: 5
  - name: Thrust load cell
    type: LOAD
    uid: 29hv
    channel: -1 # not used
    period: 5
  - name: Nitrous load cell
    type: LOAD
    uid: 29gV
    channel: -1 # not used
    period: 5
  - name: N2OMainValveSensor
    type: SERVO_STATE
    uid: 2cPc
    channel: 2
    period: -1
  - name: N2OFillValveSensor
    type: SERVO_STATE
    uid: 2cPc
    channel: 0
    period: -1
  - name: N2OVentValveSensor
    type: SERVO_STATE
    uid: 2cPc
    channel: 1
    period: -1
  - name: N2PurgeValveSensor
    type: SERVO_STATE
    uid: 2cPc
    channel: 4
    period: -1
  - name: N2PressureValveSensor
    type: SERVO_STATE
    uid: 2cPc
    channel: 3
    period: -1