# List of actor definitions
actors:

  # Valves
  - name: main_valve
    type: SERVO
    uid: 2cPc
    output: 2
    closed_position: -7500
    open_position: 6800
  - name: vent_valve
    type: SERVO
    uid: 2cPc
    output: 1
    closed_position: 0
    open_position: 5000
  - name: fill_valve
    type: SERVO
    uid: 2cPc
    output: 0
    closed_position: 0
    open_position: -7000
  - name: pressurization_valve
    type: SERVO
    uid: 2cPc
    output: 3
    closed_position: 0
    open_position: 7000
  - name: purge_valve
    type: SERVO
    uid: 2cPc
    output: 4
    closed_position: 0
    open_position: 7000

  # Solenoids
  - name: vent_solenoid
    type: SOLENOID
    uid: 2f6L
    output: 2
    closed_position: 0
    open_position: 1
  - name: fill_solenoid
    type: SOLENOID
    uid: 2f6L
    output: 1
    closed_position: 0
    open_position: 1

  # Quick Disconnect
  - name: qd_solenoid
    type: SOLENOID
    uid: 2f6L
    output: 3
    closed_position: 0
    open_position: 1
  - name: qd_servo
    type: SERVO
    uid: 2cPc
    output: 5
    closed_position: 0
    open_position: 2250

  # Misc
  - name: igniter
    type: TRIGGER
    uid: 2f6L
    output: 8
  - name: segment_display
    type: COUNTER
    uid: 256T
    output: -1
  - name: horn
    type: HORN
    uid: 2f6L
    output: 0
   # - name: light
 #   type: LIGHT
 #   uid: 2f6L
 #   output: 1

# List of sensor definitions
sensors:

  # Pressures
  - name: pressure_tank
    type: PRESSURE
    uid: 27AM
    channel: 0
    period: 100
  - name: pressure_ox_bottle
    type: PRESSURE
    uid: 27AM
    channel: 1
    period: 100
  - name: pressure_cc_pre
    type: PRESSURE
    uid: 27AQ
    channel: 1
    period: 100
  - name: pressure_n2_bottle
    type: PRESSURE
    uid: 27AQ
    channel: 0
    period: 100

  # Combustion Chamber Pressures
  - name: pressure_cc0
    type: PRESSURE
    uid: 27AG
    channel: 0
    period: 100
  - name: pressure_cc1
    type: PRESSURE
    uid: 27AG
    channel: 1
    period: 100

  # Temperatures
  - name: temp_ox
    type: TEMPERATURE
    uid: 2f1R
    channel: -1 # not used
    period: 50
  - name: temp_engine
    type: TEMPERATURE
    uid: 2eZV
    channel: -1 # not used
    period: 50

  # Load Cells
  - name: load_cell_thrust
    type: LOAD
    uid: 29hv
    channel: -1 # not used
    period: 50
  - name: load_cell_ox
    type: LOAD
    uid: 29gV
    channel: -1 # not used
    period: 50