# List of actor definitions
actors:
  - name: Horn
    type: HORN
    uid: 2f6L
    output: 0
  - name: Light
    type: LIGHT
    uid: 2f6L
    output: 1
  - name: Igniter
    type: TRIGGER
    uid: 2f6L
    output: 0
  - name: NitrousMain
    type: SERVO
    uid: 2cPc
    output: 2
  - name: NitrousVent
    type: SERVO
    uid: 2cPc
    output: 1
  - name: NitrousFill
    type: SERVO
    uid: 2cPc
    output: 0
  - name: N2Pressure
    type: SERVO
    uid: 2cPc
    output: 3
  - name: N2Purge
    type: SOLENOID
    uid: 2f6L
    output: 4
  - name: SegmentDisplay
    type: COUNTER
    uid: 256T
    output: -1

# List of sensor definitions
sensors:
  - name: Pressure 1
    type: PRESSURE
    uid: 27AM
    channel: 0
    period: 5
  - name: Pressure 2
    type: PRESSURE
    uid: 27AM
    channel: 1
    period: 5
  - name: Pressure 3
    type: PRESSURE
    uid: 27AQ
    channel: 0
    period: 5
  - name: Pressure 4
    type: PRESSURE
    uid: 27AG
    channel: 0
    period: 5
  - name: Temperatur Nitrous
    type: TEMPERATURE
    uid: 2f1R
    channel: -1 # not used
    period: 5
  - name: Temperatur Engine
    type: TEMPERATURE
    uid: 2eZV
    channel: -1 # not used
    period: 5
  - name: Thrust load cell
    type: LOAD
    uid: 29h4
    channel: -1 # not used
    period: 5
  - name: Nitrous load cell
    type: LOAD
    uid: 29gV
    channel: -1 # not used
    period: 5
  - name: Differential Nitrous pressure
    type: PRESSURE
    uid: 27AR
    channel: 1
    period: 5